### ISSUE TITLE
problem parsing fs cvs

### ISSUE THREAD

**Issue by iamruhua** [cgrates/fsock#14]
```go
isGroup, _ := regexp.MatchString("{.*}|[.*]", spltData)
isPrevGroup, _ := regexp.MatchString("{.*}|[.*]", retSplit[idx-1])
```

Should we escape the brackets?

**Comment by danbogos** [comment]
hi @iamruhua 

apologies for huge delay, issue slipped through :(.
I am not sure I understand the problem, any chance you come up with an example?

Ta,
DanB

**Comment by danbogos** [comment]
hi @iamruhua 

Since there was no reply, I will close the issue.

Please reopen once you find it actual again.

Thanks,
DanB
