### ISSUE TITLE
Support for bgapi

### ISSUE THREAD

**Issue by markose** [cgrates/fsock#7]
I've tried the general "SendCmd" for that, but it blocks infinitely when used in combination with "bgapi".
The example string I send was:
bgapi originate loopback/answer\,/ib_connect ib_connect

Sending this string via telnet session works correctly and the FS response is:
Content-Type: command/reply
Reply-Text: +OK Job-UUID: f531c865-7005-4253-8d26-9b675798db0f
Job-UUID: f531c865-7005-4253-8d26-9b675798db0f

Somehow fsock does not get the response and blocks forever.

**Comment by markose** [comment]
Maybe something like this:

//Send BG API command
func (self *FSock) SendBgApiCmd(cmdStr string, chanResEvt chan string) error {
	if err := self.ReconnectIfNeeded(); err != nil {
		return err
	}
	cmd := fmt.Sprintf("bgapi %s\n\n", cmdStr)
	self.connMutex.RLock()
	fmt.Fprint(self.conn, cmd)
	self.connMutex.RUnlock()

	// Wait for reply
	go func() {
		timer := time.NewTimer(time.Second * 1)
		select {
		case resEvent := <-self.cmdChan:
			{
				// Return result event
				chanResEvt <- resEvent
			}
		case <-timer.C:
			{
				close(chanResEvt)
			}
		}
	}()

	return nil
}

**Comment by danbogos** [comment]
@markose: thank you for your proposal. Will check it over the weekend and come back to you.

DanB

**Comment by markose** [comment]
It's not 100 percent correct, just a workaround for my use case

**Comment by danbogos** [comment]
don't worry, will make the best solution out of it.

**Comment by markose** [comment]
any updates about bg_api support?

**Comment by cgrates** [comment]
Hi @markose,

Sorry for the delay but lately 2 hands are simply not enough anymore ;). Will most probably check it again when back from holiday which should be at the end of the month.

Thanks for understanding!

DanB

**Comment by markose** [comment]
Alright,

happy holidays :-)

Kind regards,
Marko

**Comment by danbogos** [comment]
Hi @markose 

Sorry, I forgot to update the issue.
We have introduced support for bgapi a while ago. Please test it and if any issues, reopen here.

Thanks,
DanB
